### ISSUE TITLE
按照semantic_segmentation/readme教程安装环境失败。

### ISSUE THREAD

**Issue by Atlantisming** [BR-IDL/PaddleViT#102]
在最后一步
`cd PaddleViT/semantic_segmentation
pip3 install -r requirements.txt`
报错，提示如下
`(paddlevit) D:\PyWorkspace\PaddleViT\PaddleViT\semantic_segmentation>pip3 install -r requirements.txt
Collecting cityscapesScripts==2.2.0
  Using cached cityscapesScripts-2.2.0-py3-none-any.whl (472 kB)
ERROR: Could not find a version that satisfies the requirement detail==4.0 (from versions: none)
ERROR: No matching distribution found for detail==4.0`
尝试直接安装detail包
`(paddlevit) D:\PyWorkspace\PaddleViT\PaddleViT\semantic_segmentation>pip3 install detail==4.0
ERROR: Could not find a version that satisfies the requirement detail==4.0 (from versions: none)
ERROR: No matching distribution found for detail==4.0
(paddlevit) D:\PyWorkspace\PaddleViT\PaddleViT\semantic_segmentation>pip3 install detail
ERROR: Could not find a version that satisfies the requirement detail (from versions: none)
ERROR: No matching distribution found for detail`
更新pip
`(paddlevit) D:\PyWorkspace\PaddleViT\PaddleViT\semantic_segmentation>pip install --user --upgrade pip
Requirement already satisfied: pip in d:\anaconda\envs\paddlevit\lib\site-packages (21.3.1)`
仍然无法安装
`(paddlevit) D:\PyWorkspace\PaddleViT\PaddleViT\semantic_segmentation>pip3 install detail
ERROR: Could not find a version that satisfies the requirement detail (from versions: none)
ERROR: No matching distribution found for detail`
百度没有找到相关包
最后安装了details-0.2.0的工具包，不知道如何使用。

**Comment by Li-fAngyU** [comment]
@Atlantisming 
可以看下 PaddleViT/semantic_segmentation/requirements.txt 里面的内容吗。
我现在看里面并没有一个叫detail的包

**Comment by Atlantisming** [comment]
> @Atlantisming 可以看下 PaddleViT/semantic_segmentation/requirements.txt 里面的内容吗。 我现在看里面并没有一个叫detail的包
嗯嗯，忽视这个包可以正常使用，我刚看了一下，三天之前这个包被删除了~
