### ISSUE TITLE
Will Mobile-Former of PaddleViT come soon ?

### ISSUE THREAD

**Issue by August0424** [BR-IDL/PaddleViT#108]
**Describe your feature request**
Will PaddleViT recently add Mobile-Former and release pretrained weights on ImageNet? 

**Describe the reference code or paper**
Paper -> Mobile-Former: Bridging MobileNet and Transformer

**Describe the possible solution**

**Additional context**

**Comment by aiyasin** [comment]
Yes, this pretrained weights will be released soon

**Comment by wy1996-hub** [comment]
Will PaddleViT add MobileVit(as backbone) for segmentation ?

**Comment by aiyasin** [comment]
> 

It's planned, but it could take a little longer

**Comment by zhao-zi-an** [comment]
> 

你好，请问MobileFormer的预训练权重发布了吗

**Comment by wyxogo** [comment]
> > 
> 
> 你好，请问MobileFormer的预训练权重发布了吗

[https://github.com/BR-IDL/PaddleViT/tree/develop/image_classification/MobileViT#models-zoo](https://github.com/BR-IDL/PaddleViT/tree/develop/image_classification/MobileViT#models-zoo)
