### ISSUE TITLE
训练loss不下降，精度很差

### ISSUE THREAD

**Issue by Q-amazing** [BR-IDL/PaddleViT#113]
为什么我用自己的数据集按照配置单卡训练ViT，效果很差。同一份预料，我在paddle-resnet上可以达到99%精度
![Q1](https://user-images.githubusercontent.com/89431684/145359462-6668f6a0-e146-4f68-9d6e-51d8fe320940.png)
。

**Comment by xperzy** [comment]
ViT code 已经更新，建议尝试新版本的代码开展实验。

**Comment by Q-amazing** [comment]
好的，收到

**Comment by Q-amazing** [comment]
> 

我是加载了预训练模型，ViT尺寸是patch16_384，ResNet是50_vd.我调整lr=0.0001，batch_size=32，10轮精度就可以达到0.8以上。

**Comment by xperzy** [comment]
@xperzy 如果加载预训练模型，可能是训练的超参数设置需要进行调整，这个需要根据数据集特点和经验进行了。ViT本身模型较大，如果数据集规模不够，可能会出现较难收敛的情况，ViT比ResNet50要大很多。

**Comment by xperzy** [comment]
Since this is related to hyperparameter tuning, not a bug for the code, I close this issue
