### ISSUE TITLE
Support validation without create the training dataset and dataloader

### ISSUE THREAD

**Issue by xperzy** [BR-IDL/PaddleViT#115]
**Describe your feature request**
Current validation (config.EVAL is True) mode still create and load training dataset and dataloader, which is not flexible when users only have val set.

So main method needs support val mode without touching training set.

**Describe the reference code or paper**
N/A

**Describe the possible solution**
I have a fix in ViT model, which can be used to other classification model.
Please refer to commit 9a7c105 for details.

**Comment by DDXDaniel** [comment]
I'll fix it later.
