### ISSUE TITLE
Combine RandAug and AutoAug in 1 file

### ISSUE THREAD

**Issue by xperzy** [BR-IDL/PaddleViT#123]
**Describe your feature request**
There is an implementation of RandAug in  `MAE` branch, while in other models the AutoAug is implemented in `auto_augment.py`, it is more clear if the two can be combined in one file.

**Describe the reference code or paper**
N/A

**Describe the possible solution**
Combine the common functions and classes.

**Additional context**
N/A

**Comment by xperzy** [comment]
@skpig  Could you help working on this feature?

**Comment by skpig** [comment]
OK, I'll try my best :)

**Comment by xperzy** [comment]
@skpig  Please also modify other auto_augment.py files.
I'm closing this issue.
