### ISSUE TITLE
Mixup的batch size是否一定需要为偶数？

### ISSUE THREAD

**Issue by DuerWorker** [BR-IDL/PaddleViT#134]
在数据增强mixup中，Mixup类中，是否需要assert batch_size % 2 == 0，对于数据集每个epoch最后一个batch，取剩余的图像不一定可以保证所剩的数据量为偶数，在训练过程中出现训练终止的情况。或者可以考虑采用drop_last进行设置。

**Comment by DDXDaniel** [comment]
你好@DuerWorker， batch size一般为偶数(2的幂)主要是方便性能优化，因为线程数通常是2^n这种数字。所以建议设置drop_last=True以防止训练终止。

**Comment by xperzy** [comment]
This issue has been explained clearly, so I close this issue
