### ISSUE TITLE
希望可以增加参数来允许自定义输出路径

### ISSUE THREAD

**Issue by SigureMo** [BR-IDL/PaddleViT#142]
**Describe your feature request**

目前貌似只有少数模型（Focal_Transformer、MobileFormer）是可以通过参数自定义 output 路径的，但自定义输出路径的需求是很常见的（比如 AI Studio 的脚本任务必须将 log 输出到指定目录）。虽然改配置也能做到这一点，但是比较麻烦，因此希望其余模型也支持通过参数自定义 output 路径。

**Describe the reference code or paper**

None

**Describe the possible solution**

增加参数 `-output`，见 PR #143 

**Additional context**

**Comment by xperzy** [comment]
Good Work!
