### ISSUE TITLE
 Pale-Shaped Attention

### ISSUE THREAD

**Issue by Seperendity** [BR-IDL/PaddleViT#151]
请问对给定一个输入特征图，是怎么将其分割成多个相同大小的pale的？论文中pale的维度是一个二维的，这个分割成相同大小的pale具体是在维度上怎么操作的呢，我看论文中的图没有体现分割出了多个pale，能以图中h=9，sr=sw=3为例说明一下嘛。谢谢

**Comment by xperzy** [comment]
Thanks for the issue !

@wutianyiRosun  Could you help answer this question?

**Comment by wutianyiRosun** [comment]
@Seperendity 你可以把Figure1 (e)的每两个粉色行（或者列）之间的两个白色行(或者列）用别的两种颜色进行着色，就可以得到三个pale（三种不同颜色）

**Comment by Seperendity** [comment]
@wutianyiRosun @xperzy 感谢解答，和我之后的理解一致。

**Comment by xperzy** [comment]
Since the issue has been explained clearly, I close this issue.
