### ISSUE TITLE
请问paddlevit里面的模型可以部署吗？比如转成onnx?

### ISSUE THREAD

**Issue by wstchhwp** [BR-IDL/PaddleViT#163]

**Comment by xperzy** [comment]
Thanks for the issue!
paddlevit的模型基本上没有依赖第三方的包，转成onnx应该没有问题。
如果在转换过程中有任何问题请提issue我们一起看下。

**Comment by wstchh** [comment]
好的，谢谢开源，期待这个repo更新更多的模型！
