### ISSUE TITLE
predict.py没有嘛？

### ISSUE THREAD

**Issue by wstchhwp** [BR-IDL/PaddleViT#164]
给的案例只有train.py和eval.py文件，没有看到predict.py文件

**Comment by xperzy** [comment]
Thanks for the commit. 
我新上传了一个简单的说明文档介绍如何使用paddlevit实现预测方法，
https://github.com/BR-IDL/PaddleViT/blob/develop/docs/paddlevit-predict-cn.md

简要的流程：
1. 在`datasets.py`中：
    - 增加定义目标数据集的class
    - 增加`get_test_transforms`方法实现数据预处理
    - `get_dataset`方法中增加目标数据集的调用方法
2. 在 `main_single_gpu.py`中：
    - 在数据集定义的部分，修改为目标数据集
    - 增加`predict`方法，可以参考并修改`validate`方法，去掉criterion等需要label信息的操作，方法返回预测结果
    - 在主方法中，修改validate调用predict，然后增加自己对预测结果的处理（例如写文件等操作）

**Comment by wstchhwp** [comment]
检测的流程也是有一样的吧。

**Comment by xperzy** [comment]
> 检测的流程也是有一样的吧。

基本上是的，目前检测的代码还没有非常完善，遇到问题请随时提issue！
