### ISSUE TITLE
纯小白，关于DeiT准确率不高的问题

### ISSUE THREAD

**Issue by GeYuYao-hub** [BR-IDL/PaddleViT#167]
您好，我是一名大二学生，近期在利用paddle撰写一篇deit的论文，我通过看您的课找到了这个项目，我将DeiT在aistudio上运行，除了将dataset设置为cifar10之外没有修改任何的参数，但是模型的准确率一直稳定在10%左右，我很emo不知道哪里出了问题，请问是我的使用方法不对吗？

**Comment by xperzy** [comment]
Hello, 感谢使用项目！ 目前咱们DeiT应该没有提供Cifar10的预训练模型，提供的可下载模型是在imagenet上训练的。 如果是使用cifar10数据重新进行训练，请提供一下更多的训练相关信息，方便我们定位问题， 谢谢！

**Comment by GeYuYao-hub** [comment]
哦！那我应该先用cnn去训练一个老师模型，然后再来训练对嘛

**Comment by xperzy** [comment]
1. 建议去找一个paddle的模型，已经在cifar10上训练好即可，需要模型文件(.py)和预训练权重文件(.pdparams)。
2. 可能需要修改dataset.py里的数据处理部分，目前的数据处理是针对imagenet的，需要调整为cifar10的
3. 训练的超参数可能也需要进一步调整。

**Comment by GeYuYao-hub** [comment]
好的！感谢朱老师！
