### ISSUE TITLE
模型的验证时，滑动窗口验证有什么用？

### ISSUE THREAD

**Issue by peach-xiao** [BR-IDL/PaddleViT#172]
开发者团队您好！我最近使用了PaddleViT 框架中swinTransformer 语义分割Segmentation中的upernet_swin_tiny训练自己的数据集，遇到了以下问题不是很明白

问题1：训练过程中保存了以xxxx.pdparams和xxxx.pdopt为后缀的模型文件，第一个是用于加载评估模型用的，请问xxxx.pdopt有什么用呢？
        if (cur_iter % config.SAVE_FREQ_CHECKPOINT == 0 or cur_iter == config.TRAIN.ITERS) and local_rank == 0:
            current_save_weigth_file = os.path.join(config.SAVE_DIR,
                                                    "iter_{}_model_state.pdparams".format(cur_iter))
            current_save_opt_file = os.path.join(config.SAVE_DIR,
                                                 "iter_{}_opt_state.pdopt".format(cur_iter))
            paddle.save(model.state_dict(), current_save_weigth_file)    ---》》》》》保存文件
            paddle.save(optimizer.state_dict(), current_save_opt_file)  --》》》》》保存文件
            save_models.append([current_save_weigth_file,
                                current_save_opt_file])

问题2：在验证的时候，有个策略是通过滑动窗口进行推断，即PaddleViT-develop\semantic_segmentation\src\api\infer.py里的slide_inference（）函数，我没有明白这个滑动窗口推断的意义何在，并且我也尝试了更改滑动步长在进行验证，即在配置文件.yaml里面，VAL ：STRIDE_SIZE: [341，341]， 我发现验证结果都是一样的。用滑动窗口进行验证和对整张图片直接进行验证有什么不同呢？是为了让验证的速度更快吗？

希望可以得到你们的帮助，您的一句简单的回复将是我前进的最大动力，感谢~ @xperzy  @wutianyiRosun

**Comment by xperzy** [comment]
Thanks for the issue.   我们收到了您的问题，并会尽快回复。  我理解在分割验证时候使用滑窗，会在一定程度上提升性能，但是会带来运行时间上的增加，有些论文中也report了滑窗的结果，如果不使用滑窗可能会无法对齐论文中的结果。   @wutianyiRosun 麻烦你看下这个问题看是否有补充

**Comment by wutianyiRosun** [comment]
@xiaoguoguo2018 关于问题1， xxxx.pdopt是用来保存optimizer的相关数据，方便用于resume训练  
关于问题2, @xperzy 的回复是准确的

**Comment by xiaoguoguo2018** [comment]
对于滑动窗口验证，我还有以下问题

1. 请问一下滑动窗口验证的步长是否会影响模型验证的结果呢？比如说我的验证集图片大小是512x512，当我的滑动窗口步长分别是256和341或者别的步长，加载同样的权重模型，验证的结果是否不同？

2.设置滑动窗口的步长有什么注意事项吗？我注意到不同的数据集，裁剪窗口的大小和对于的步长都有所不同。如在yaml文件里设置验证Val的参数：pascal_contex数据集 验证的CROP_SIZE: [480,480], STRIDE_SIZE: [320,320]，adk数据集   CROP_SIZE: [512,512]， STRIDE_SIZE: [341,341] ，cityscapes数据集    CROP_SIZE: [768,768] STRIDE_SIZE: [512,512]
验证时设置的裁剪窗口大小和步长是有对应关系的吗？设置其他的步长是否会对验证有影响

3. 滑动窗口验证时通过将图片根据步长将验证集的图片裁剪成重叠的多个小块，然后分别将这些小块送入模型进行验证求取结果，不知道我这样的理解是否正确呢？

感谢您的耐心回复~ @xperzy @wutianyiRosun
