### ISSUE TITLE
Paddle ViT框架是否能够提供新手入门教程？

### ISSUE THREAD

**Issue by peach-xiao** [BR-IDL/PaddleViT#173]
PaddlePaddle很多的系列都有相应的新手教程，如PaddleSeg, PaddleDetction。PaddleViT框架包含了计算机视觉语义分割和自然语言处理NLP的一些知识。目前我是PaddleViT用做的分割，我发现不管是训练还是验证还是和PaddleSeg有些细节不同，为了解决和弄清楚一些细节问题，我花费了很多的时间在上面。如果可以出一份新手入门的框架使用就更好了。例如：包括模型的加载，数据集的可视化，模型的预测说明等等。

愿Paddle团队在未来越做越好！

**Comment by xperzy** [comment]
感谢提出非常有用的建议，您是特指分割的教程还是整个ppvit（PaddleViT简称）的，如果是后者，在 
https://github.com/BR-IDL/PaddleViT/tree/develop/docs
https://github.com/BR-IDL/PaddleViT/tree/develop/edu
中我们都有提供一些ppvit的使用教程和课程，如果还有其他问题或者我们还有哪些可以补充进来的，欢迎随时提issue！

感谢！

**Comment by peach-xiao** [comment]
> 感谢提出非常有用的建议，您是特指分割的教程还是整个ppvit（PaddleViT简称）的，如果是后者，在 https://github.com/BR-IDL/PaddleViT/tree/develop/docs https://github.com/BR-IDL/PaddleViT/tree/develop/edu 中我们都有提供一些ppvit的使用教程和课程，如果还有其他问题或者我们还有哪些可以补充进来的，欢迎随时提issue！
> 
> 感谢！


非常感谢您的帮助！我期待的就是PaddleViT的使用文档教程，之前没有注意docs文件夹里的教程，现在我的问题已解决。
