### ISSUE TITLE
用于PaddleViT模型的Resnet预训练权重哪里下载？

### ISSUE THREAD

**Issue by peach-xiao** [BR-IDL/PaddleViT#174]
在PaddleViT用于语义分割的Trans2Seg模型，配置文件里需要使用resnet50c.pdparams的预训练权重文件，想问下是否可以提供一下下载方式？如果有resnet50, resnet101，resnet50c, resnet101c等系列模型文件能够提供一份吗？
![image](https://user-images.githubusercontent.com/40911688/158577078-a07967bd-4893-4cfe-aaf2-13ba00f5cd1a.png)

感谢！@xperzy

**Comment by xperzy** [comment]
@xiaoguoguo2018  Thanks for the issue.    @wutianyiRosun Could you provide the above links for resnets pretrain weigths?

**Comment by wutianyiRosun** [comment]
@xiaoguoguo2018  可以到PaddleClass下载

**Comment by GuoQuanhao** [comment]
![image](https://user-images.githubusercontent.com/49911294/162356818-68c666d5-c973-49f9-8d20-5b6724adf7b1.png)
在这里下载，Readme首页Trans10kV2部分有列出
