### ISSUE TITLE
BEIT模型在paddle混合精度训练下 前向出现nan。

### ISSUE THREAD

**Issue by Lemonahahah** [BR-IDL/PaddleViT#178]
BEIT模型在paddle混合精度训练下 前向出现nan。

**Comment by Lemonahahah** [comment]
patch embeding阶段就已经存在nan了：
<img width="667" alt="image" src="https://user-images.githubusercontent.com/94953627/159625907-c73cdb84-d123-43df-9da4-37192b62a683.png">

**Comment by xperzy** [comment]
Thanks for the issue, 我们已经收到您的反馈，希望您能够提供更多信息，例如输入数据，模型等，我们会尽快安排修复。

**Comment by Lemonahahah** [comment]
可以给个HI的账号吗？厂内用户，想咨询几个问题。
发件人: xperzy ***@***.***>
答复: BR-IDL/PaddleViT ***@***.***>
日期: 2022年3月23日 星期三 下午5:03
收件人: BR-IDL/PaddleViT ***@***.***>
抄送: "He,Feng(KG)" ***@***.***>, Author ***@***.***>
主题: Re: [BR-IDL/PaddleViT] BEIT模型在paddle混合精度训练下 前向出现nan。 (Issue #178)


Thanks for the issue, 我们已经收到您的反馈，希望您能够提供更多信息，例如输入数据，模型等，我们会尽快安排修复。

**Comment by xperzy** [comment]
我这更新了一版代码，请查看https://github.com/BR-IDL/PaddleViT/tree/develop/image_classification/BEiT

**Comment by xperzy** [comment]
好的！

zhuyu05
