### ISSUE TITLE
MaskFormer support

### ISSUE THREAD

**Issue by shuxp** [BR-IDL/PaddleViT#208]
**Describe your feature request**
Add MaskFormer to paddlevit.

**Describe the reference code or paper**
https://arxiv.org/abs/2107.06278

**Describe the possible solution**
iMaybe there are some implementations with pytorch format, but paddle format is better...

**Comment by xperzy** [comment]
Hello, thanks for the issue. 
We are evaluating the model implementation and will update once it is done.
