### ISSUE TITLE
请问有提供模型训练的日志吗？

### ISSUE THREAD

**Issue by wmkai** [BR-IDL/PaddleViT#211]
比如分类中的topformer模型

**Comment by xperzy** [comment]
Hello， thanks for the issue， topformer我们正在训练中，由于机器资源有限，可能还需要一段时间，一旦完成paddle上的train from scratch，我们会及时更新模型和log。 如果有特殊需求可以单独联系我！谢谢！

**Comment by wmkai** [comment]
> Hello， thanks for the issue， topformer我们正在训练中，由于机器资源有限，可能还需要一段时间，一旦完成paddle上的train from scratch，我们会及时更新模型和log。 如果有特殊需求可以单独联系我！谢谢！

谢谢回复，我看仓库里好像已经有topformer分类模型的ckpt了，但是没有log

**Comment by xperzy** [comment]
> > Hello， thanks for the issue， topformer我们正在训练中，由于机器资源有限，可能还需要一段时间，一旦完成paddle上的train from scratch，我们会及时更新模型和log。 如果有特殊需求可以单独联系我！谢谢！
> 
> 谢谢回复，我看仓库里好像已经有topformer分类模型的ckpt了，但是没有log

Hello, 目前提供的模型是从官方模型转到paddle下的，使用paddlevit从零开始训练的模型文件和log我刚刚更新了，[here](https://github.com/BR-IDL/PaddleViT/blob/develop/image_classification/TopFormer/README.md)

由于原文中没有提供具体的训练细节和参数，我这边目前base模型能够得到 **74.22%** 的acc，如果需要完全复现论文准确率，建议增大Epoch数量，或者对其他超参数进行调节。

**Comment by wmkai** [comment]
> > > Hello， thanks for the issue， topformer我们正在训练中，由于机器资源有限，可能还需要一段时间，一旦完成paddle上的train from scratch，我们会及时更新模型和log。 如果有特殊需求可以单独联系我！谢谢！
> > 
> > 
> > 谢谢回复，我看仓库里好像已经有topformer分类模型的ckpt了，但是没有log
> 
> Hello, 目前提供的模型是从官方模型转到paddle下的，使用paddlevit从零开始训练的模型文件和log我刚刚更新了，[here](https://github.com/BR-IDL/PaddleViT/blob/develop/image_classification/TopFormer/README.md)
> 
> 由于原文中没有提供具体的训练细节和参数，我这边目前base模型能够得到 **74.22%** 的acc，如果需要完全复现论文准确率，建议增大Epoch数量，或者对其他超参数进行调节。

非常感谢！另外，topformer官方仓库里放出的分类模型的ckpt里有保存了训练的超参数。
