### ISSUE TITLE
说明文档在数据准备阶段的Bug

### ISSUE THREAD

**Issue by VBPython** [BR-IDL/PaddleViT#217]
**Describe the bug**

**To Reproduce**
2. When the cace '...'
2. Run '....'

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Paddle Version: [e.g. 2.1.0]
 - Python Version [e.g. 3.6]
- GPU/CPU mode [e.g. cpu]

**Additional context**
在做迁移学习FineTuing任务时，要先做Data Preparation，并将数据集按照ImageNet2012的格式进行调整，同时形成val_list.txt等。开源者十分贴心的附上了相关val_list.txt跳转下载链接。
![image](https://user-images.githubusercontent.com/45344296/180589963-e59d3794-3db0-402a-a51a-e62a0aa0f321.png)
但是，链接的密码接入有误，无法实现下载。
![image](https://user-images.githubusercontent.com/45344296/180589932-892df808-9487-4cdf-a76e-e5ba27d30730.png)
实际该链接的密码为：a4vm，而不是a4vm?pwd=a4vm。
望对跳转链接进行优化，谢谢。

**Comment by xperzy** [comment]
非常感谢提出上面的问题，请问是哪一个或者哪几个链接发现了此问题？

?pwd=a4vm应该是网盘的免输验证码的用法，我这边试了几个链接可以正常访问，如果有发现具体那个页面有问题，我来修改为正确格式。
谢谢！
