### ISSUE TITLE
求train_list.txt, val_list.txt

### ISSUE THREAD

**Issue by caikw0602** [BR-IDL/PaddleViT#221]
能否提供一下imagenet2012数据集中的train_list.txt和val_list.txt? 感激不尽

**Comment by xperzy** [comment]
请参考https://github.com/BR-IDL/PaddleViT/tree/develop/image_classification/ViT#data-preparation
页面中的link:
- `train_list.txt`: list of relative paths and labels of training images. You can download it from: [google](https://drive.google.com/file/d/10YGzx_aO3IYjBOhInKT_gY6p0mC3beaC/view?usp=sharing)/[baidu](https://pan.baidu.com/s/1G5xYPczfs9koDb7rM4c0lA?pwd=a4vm?pwd=a4vm)
- `val_list.txt`: list of relative paths and labels of validation images. You can download it from: [google](https://drive.google.com/file/d/1aXHu0svock6MJSur4-FKjW0nyjiJaWHE/view?usp=sharing)/[baidu](https://pan.baidu.com/s/1TFGda7uBZjR7g-A6YjQo-g?pwd=kdga?pwd=kdga) 

请问是哪个页面没有展示链接？

**Comment by caikw0602** [comment]
朱老师，您好，很喜欢您的课程，学习过您的《从零开始学视觉Transformer》，也听过您在论文复现营中的代码实现讲解，深入浅出，让我受益非浅，借这个机会跟您说下感谢！

谢谢朱老师的回复，是我自己没有找到data-preparation的链接，我是从源码datasets.py中class ImageNet2012Dataset的注释中找的链接，那个链接打不开，地址跟这个也不相符，建议修改一下吧，谢谢啦！

另外，我看现在的paddleViT 的项目中大部分模型都是提供了main_multi_gpu.py，请问可以提供一个main_single_gpu.py给我们学习吗？我记得以前有的，但是现在好像取消了？

**Comment by xperzy** [comment]
感谢回复。
1. 已经在dataset.py 中修改comment的链接。
2. main_multi_gpu.py 目前已经支持单GPU，只需要使用 CUDA_VISIBLE_DEVICES=0 就可以开启，如果遇到问题欢迎提issue。

**Comment by caikw0602** [comment]
感谢回复，谢谢
