### ISSUE TITLE
[Semantic Segmentation] BEiT-L

### ISSUE THREAD

**Issue by rock4you** [BR-IDL/PaddleViT#50]
Does this model reproduced so far ?
BEiT-L (ViT+UperNet, ImageNet-22k pretrain) mIoU-57.0%
https://paperswithcode.com/paper/beit-bert-pre-training-of-image-transformers

**Comment by lmk123568** [comment]
目前暂未支持，敬请期待后续！

**Comment by lmk123568** [comment]
> Does this model reproduced so far ? BEiT-L (ViT+UperNet, ImageNet-22k pretrain) mIoU-57.0% https://paperswithcode.com/paper/beit-bert-pre-training-of-image-transfo

**Comment by xperzy** [comment]
@GuoQuanhao @wutianyiRosun Could you guys help evaluate if we can add this model?

**Comment by wutianyiRosun** [comment]
@rock4you  We are planning to reproduce BEiT-L.
