### ISSUE TITLE
small bugs

### ISSUE THREAD

**Issue by rock4you** [BR-IDL/PaddleViT#52]
https://github.com/BR-IDL/PaddleViT/blob/develop/semantic_segmentation/src/models/backbones/cswin_transformer.py#L537

**Comment by xperzy** [comment]
Thanks for the issue! 

https://github.com/BR-IDL/PaddleViT/blob/e8dcc35556757b7db27b218cdd1d4410d2943755/semantic_segmentation/src/models/backbones/cswin_transformer.py#L537

I'm closing this issue.
