### ISSUE TITLE
Error about Installation in README

### ISSUE THREAD

**Issue by skpig** [BR-IDL/PaddleViT#58]
https://github.com/BR-IDL/PaddleViT/blob/9877f367b3829516c30d105dcc21c4057c82f633/README.md?plain=1#L155-L162

I can't find package `detail` and `yaml` in PyPI.

**Comment by xperzy** [comment]
@GuoQuanhao could you help handle this issue？

**Comment by DDXDaniel** [comment]
Hello, this may happens when you use Python3, so please use ```pip install pyyaml```  instead or you can use Python2 to install ```yaml``` and ```detail```.

**Comment by xperzy** [comment]
The readme files are now updated so I close the issue.
