### ISSUE TITLE
Whether a class number parameter is missing in the mixup of training code?

### ISSUE THREAD

**Issue by cjh3020889729** [BR-IDL/PaddleViT#64]
**Describe the question**
In the classification directory, when MIXUP prerequisites are performed in `main_single_gpu / main_multi_gpu.py`, the `NUM_CLASSES` parameter is not passed, resulting in a `non-IMAGENET1K` data set to load, the existing `main_single_gpu / main_multi_gpu.py` will result in `an error`——since the number of categories of the current model is not equal to 1000, the Mixup default classification number is still 1000, which will cause loss calculations that cannot be performed at this time.

**Expected behavior**
Introducing the class number parameters, so that the training code is easier to use.

**Screenshots**
![mixup实例时为初始化类别数](https://user-images.githubusercontent.com/55022974/142803843-54018aa5-02d7-4ec1-9452-00ef850d1625.png)

**Comment by xperzy** [comment]
Thanks for the issue, it is indeed a problem if using other dataset where num_class is not 1000.
We are fix this bug ASAP.
