### ISSUE TITLE
There is a flaw in the notes

### ISSUE THREAD

**Issue by Fan-Zhixuan** [BR-IDL/PaddleViT#70]
https://github.com/BR-IDL/PaddleViT/blob/develop/image_classification/SwinTransformer/swin_transformer.py line224
The size of the tensor should be '2, window_h * window_w, window_h * window_w',not '2, window_h * window_w, window_h * window_h'

**Comment by xperzy** [comment]
Thanks for the issue. @jarygrace ,could you please check this issue?

**Comment by jarygrace** [comment]
Thanks for the issue, it has been modified.
