### ISSUE TITLE
一个小bug，datasets.Cifar10 的mode应该是test而不是val

### ISSUE THREAD

**Issue by wzh326** [BR-IDL/PaddleViT#81]
PaddleViT/image_classification/SwinTransformer/datasets.py 下
![1](https://user-images.githubusercontent.com/79301727/144043607-7159e52b-c00d-4211-9c5e-0b44eab41866.JPG)
在paddle的文档中，datasets.Cifar10 的预测mode 应该为'test'而不是val
![2](https://user-images.githubusercontent.com/79301727/144043839-72d7383b-5752-4046-8452-709a2fa39e80.JPG)
因此我将代码改为
![3](https://user-images.githubusercontent.com/79301727/144043987-65cc6a2b-51d1-4020-9fab-3408add467d2.JPG)
就可以正常跑通了

**Comment by libertatis** [comment]
是的，`paddle.vision.datasets` 里 [Cifar 数据集](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/vision/datasets/cifar.py) 的 `mode` 取值是 `['train', 'test']`。
再补充一下，这里为了统一数据集的加载，`ImageNet2012Dataset` 的 `mode` 取值也应该改成 `['train', 'test']` ~

**Comment by GuoQuanhao** [comment]
感谢指正，这确实是一个bug
