### ISSUE TITLE
PaddleViT-Seg教程文档中存在的小问题

### ISSUE THREAD

**Issue by richarddddd198** [BR-IDL/PaddleViT#82]
文档中多处还使用“SETR”，但是目录文件夹是小写
![FireShot Capture 009 - PaddleViT_semantic_segmentation_configs_setr at develop · BR-IDL_Padd_ - github com](https://user-images.githubusercontent.com/63178095/144069312-f99ae537-b892-4518-b003-c974eb2cf08d.png)
【原文】
CUDA_VISIBLE_DEVICES=0 python3  train.py \
    --config ./configs/**SETR**/SETR_MLA_Large_480x480_80k_pascal_context_bs_8.yaml
【应修改】
CUDA_VISIBLE_DEVICES=0 python3  train.py \
    --config ./configs/**setr**/SETR_MLA_Large_480x480_80k_pascal_context_bs_8.yaml

**Comment by xperzy** [comment]
Thanks for the issue!   

@wutianyiRosun Could you check and update the docs?

**Comment by wutianyiRosun** [comment]
@richarddddd198  Thanks for your pointing this out. Fixed

**Comment by wutianyiRosun** [comment]
@xperzy Done.
