### ISSUE TITLE
ViT模型验证时要求数据集必须有训练集和验证集不太合理

### ISSUE THREAD

**Issue by xnli** [BR-IDL/PaddleViT#87]
**Describe the bug**
在使用ViT基于Imagenet2012数据集进行模型验证时，因为数据集比较大，仅下载了验证数据集。执行模型验证命令，报错，提示没有训练集数据。

经排查，
main_single_gpu.py 在进行模型验证前，需要先加载训练集和验证集。

建议单独增加一个模型验证的脚本。

**Comment by xperzy** [comment]
Thanks for the issue!  
Yes, that is a real problem if someone only needs to run the validation without touching the training data. 

I will fix this and update the code as soon as possible!

**Comment by lmk123568** [comment]
> **Describe the bug** 在使用ViT基于Imagenet2012数据集进行模型验证时，因为数据集比较大，仅下载了验证数据集。执行模型验证命令，报错，提示没有训练集数据。
> 
> 经排查， main_single_gpu.py 在进行模型验证前，需要先加载训练集和验证集。
> 
> 建议单独增加一个模型验证的脚本。

你的建议非常重要

**Comment by xperzy** [comment]
@xnli This issue has been fixed in ViT, will update to other models asap.
Please see commit 9a7c105 for detailed changes.

I will start a new issue to update other main scripts, so I close this issue
