### ISSUE TITLE
PaddleViT-Seg安装requirements.txt依赖库时出现问题

### ISSUE THREAD

**Issue by richarddddd198** [BR-IDL/PaddleViT#89]
**Describe the bug**
PaddleViT-Seg的requirements.txt文档中需要安装的依赖库有如下：

- cityscapesScripts==2.2.0
- detail==4.0
- numpy==1.20.3
- opencv-python==4.5.2.52
- scipy==1.6.3
- yacs==0.1.8

问题一：
没有**detail** 这个库
<img width="448" alt="微信截图_20211202203427" src="https://user-images.githubusercontent.com/63178095/144438163-53c3a793-d586-4eba-80f8-a7e7be060bf5.png">
自己解决方式：删除detail

问题二：
opencv-python库没有4.5.2.52这个版本
<img width="440" alt="微信截图_20211202203715" src="https://user-images.githubusercontent.com/63178095/144438505-e68fab73-122b-412d-bea0-de5095bb632a.png">
自己解决方式：更换opencv-python版本

**Comment by xperzy** [comment]
@wutianyiRosun Could you fix the issue in the readme?

**Comment by xperzy** [comment]
@richarddddd198 Thanks for the issue, you can refer to the paddlevit main readme to install detail if needed.

The detail package could be installed by the following script:
```
git clone https://github.com/ccvl/detail-api
cd detail-api/PythonAPI
make
make install

```

**Comment by richarddddd198** [comment]
> @richarddddd198 Thanks for the issue, you can refer to the paddlevit main readme to install detail if needed.
> 
> The detail package could be installed by the following script:
> 
> ```
> git clone https://github.com/ccvl/detail-api
> cd detail-api/PythonAPI
> make
> make install
> ```
多谢解疑，在Ai Studio BML环境中，用以上方法安装detail报错无法正常安装。但是没有这库，暂不影响使用PaddleViT-Seg进行训练和验证。

**Comment by flyinggx** [comment]
### 经典版AiStudio
**1. 在notebook中安装detail时，按照教程命令安装detail失败**
![image](https://user-images.githubusercontent.com/50612571/144537548-ef826ee7-93ac-4b60-9063-d47d5cf25dc3.png)

**2.在teminal安装detail时，显示gcc有问题，需要重新安装，但是AiStudio没有相应权限安装gcc**
![image](https://user-images.githubusercontent.com/50612571/144538735-98464ecf-c91c-493c-8a06-3659ac206bc2.png)

**Comment by wutianyiRosun** [comment]
@flyinggx  gcc version=5.2.0. 如果你在AI Studio上安装or更新GCC有问题，请联系AI Studio的同学哈。或者你用你自己的机器试试
