### ISSUE TITLE
关于README中命令行参数和Usage模型加载的问题

### ISSUE THREAD

**Issue by libertatis** [BR-IDL/PaddleViT#92]
我发现 `PaddleViT` 所有模型中的 `README.md` 都存在两个问题（以下均以 [PaddleViT/image_classification/BEiT/](https://github.com/BR-IDL/PaddleViT/blob/develop/image_classification/BEiT/README.md) BEiT 模型的 `README.md` 为例）：
- 其一，`Usage` 示例代码中，加载预训练权重时少了后缀 `.pdparams`，而且注释中提到 `.pdparams is NOT needed` 也是不对的，应该是在下面的命令行参数中 `-pretrained` 的值是不需要  `.pdparams`，二者搞混了。
```python
from config import get_config
from beit import build_beit as build_model
# config files in ./configs/
config = get_config('./configs/beit_base_patch16_224.yaml')
# build model
model = build_model(config)
# load pretrained weights, .pdparams is NOT needed
model_state_dict = paddle.load('./beit_base_patch16_224_ft22kto1k')
model.set_dict(model_state_dict)
```
应该讲注释注释中的 `, .pdparams is NOT needed` 删去，并在模型加载时，加上后缀 `.pdparams`：
```python
from config import get_config
from beit import build_beit as build_model
# config files in ./configs/
config = get_config('./configs/beit_base_patch16_224.yaml')
# build model
model = build_model(config)
# load pretrained weights
model_state_dict = paddle.load('./beit_base_patch16_224_ft22kto1k.')
model.set_dict(model_state_dict)
```

- 其二，在 `Evaluation` 和 `Training` 的命令行参数值多加了一个单引号，如果在终端直接执行，会出现 `FileNotFoundError` 错误：
```python
FileNotFoundError: [Errno 2] No such file or directory: "'./configs/beit_base_patch16_224.yaml'"
```
我之前在终端预训模型训练和验证的命令时，出现过这个错误，群里也有其他同学出现了这样的问题。出现这个错误的原因是因为 `argparse` 在解析命令行参数时，为字符串类型的参数值自动加上了一个双引号。所以，在为命令行参数赋值时，不需要加上引号。所以，应该去掉 `Evaluation` 和 `Training` 命令行参数值中的单引号。
单 `GPU` 验证：
```shell
CUDA_VISIBLE_DEVICES=0 \
python main_single_gpu.py \
    -cfg='./configs/beit_base_patch16_224.yaml' \
    -dataset='imagenet2012' \
    -batch_size=16 \
    -data_path='/dataset/imagenet' \
    -eval \
    -pretrained='./beit_base_patch16_224_ft22kto1k'
```
我修改为：
```shell
CUDA_VISIBLE_DEVICES=0 \
python main_single_gpu.py \
    -cfg=./configs/beit_base_patch16_224.yaml \
    -dataset=imagenet2012 \
    -batch_size=16 \
    -data_path=/path/to/dataset/imagenet/val \
    -eval \
    -pretrained=/path/to/pretrained/model/beit_base_patch16_224_ft22kto1k  # .pdparams is NOT needed
```
多 `GPU` 验证：
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python main_multi_gpu.py \
    -cfg='./configs/beit_base_patch16_224.yaml' \
    -dataset='imagenet2012' \
    -batch_size=16 \
    -data_path='/dataset/imagenet' \
    -eval \
    -pretrained='./beit_base_patch16_224_ft22kto1k'

```
我修改为：
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python main_multi_gpu.py \
    -cfg=./configs/beit_base_patch16_224.yaml \
    -dataset=imagenet2012 \
    -batch_size=16 \
    -data_path=/path/to/dataset/imagenet/val \
    -eval \
    -pretrained=/path/to/pretrained/model/beit_base_patch16_224_ft22kto1k  # .pdparams is NOT needed

```
单 `GPU` 训练：
```shell
CUDA_VISIBLE_DEVICES=0 \
python main_single_gpu.py \
  -cfg='./configs/beit_base_patch16_224.yaml' \
  -dataset='imagenet2012' \
  -batch_size=32 \
  -data_path='/dataset/imagenet' \
```
我修改为：
```shell
CUDA_VISIBLE_DEVICES=0 \
python main_single_gpu.py \
  -cfg=./configs/beit_base_patch16_224.yaml \
  -dataset=imagenet2012 \
  -batch_size=32 \
  -data_path=/path/to/dataset/imagenet/train \
```
多 `GPU` 训练：
```shell
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python main_multi_gpu.py \
    -cfg='./configs/beit_base_patch16_224.yaml' \
    -dataset='imagenet2012' \
    -batch_size=16 \
    -data_path='/dataset/imagenet' \ 

```
我修改为：
```shell 
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python main_multi_gpu.py \
    -cfg=./configs/beit_base_patch16_224.yaml \
    -dataset=imagenet2012 \
    -batch_size=16 \
    -data_path=/path/to/dataset/imagenet/train \ 
```
一会儿，我再提交个 `PR`，请官方审查~

**Comment by xperzy** [comment]
感谢提issue！ 非常有用！ `.pdparams` 的问题确实是readme有问题。  script的问题，我这边没有发现类似的问题， 是因为terminal的版本或者平台不一样的问题吗？  我这边linux shell单引号不会有报错。

**Comment by libertatis** [comment]
> 感谢提issue！ 非常有用！ `.pdparams` 的问题确实是readme有问题。 script的问题，我这边没有发现类似的问题， 是因为terminal的版本或者平台不一样的问题吗？ 我这边linux shell单引号不会有报错。

我的操作系统是：Windows 10，版本号为 20H2
命令行终端是：Windows Terminal，版本号为 1.11.2921.0
我没在 Linux 操作系统下测试，不过不带引号的话，在 Linux 系统下应该也不会报错，以前在Linux 终端运行命令的时候，参数也没加过引号。所以建议命令行参数还是统一改成不带引号的会比较好~

**Comment by libertatis** [comment]
噢，我的意思是，直接把命令复制到终端运行，参数加引号的话会报错，不是在终端运行`.sh` 脚本会报错~

**Comment by skpig** [comment]
我尝试了在Pycharm集成终端里运行单GPU训练的命令，但是并没有发生所述情况
```
CUDA_VISIBLE_DEVICES=0 \
python main_single_gpu.py \
  -cfg='./configs/beit_base_patch16_224.yaml' \
  -dataset='imagenet2012' \
  -batch_size=32 \
  -data_path='./dataset/imagenet' \
```
但是如果选择使用pycharm配置运行文件，并设置命令行参数为
```
-cfg='./configs/vit_base_patch16_224_finetune.yaml'
-dataset
imagenet2012
-batch_size=2
-data_path='./dataset/imagenet'
```
会出现报错`FileNotFoundError: [Errno 2] No such file or directory: "'./configs/vit_base_patch16_224_finetune.yaml'"`

**Comment by libertatis** [comment]
> > 感谢提issue！ 非常有用！ `.pdparams` 的问题确实是readme有问题。 script的问题，我这边没有发现类似的问题， 是因为terminal的版本或者平台不一样的问题吗？ 我这边linux shell单引号不会有报错。
> 
> 我的操作系统是：Windows 10，版本号为 20H2 命令行终端是：Windows Terminal，版本号为 1.11.2921.0 我没在 Linux 操作系统下测试，不过不带引号的话，在 Linux 系统下应该也不会报错，以前在Linux 终端运行命令的时候，参数也没加过引号。所以建议命令行参数还是统一改成不带引号的会比较好~

不好意思，我说错了。我用的是 `PyCharm` 开发环境，是在 `PyCharm` 终端运行命令，如果参数值加引号会出现 `FileNotFoundError` 的异常。其他终端, `Windows Terminal` 和 `Git bash` 加引号不会出现这个异常。如果不加引号的话，所有的终端运行都没有问题。非常抱歉~

**Comment by libertatis** [comment]
我使用的 PyCharm 版本是 `2020.1.5(Professional Edition)` ~

**Comment by skpig** [comment]
我用的是Pycharm 2021.2

**Comment by SigureMo** [comment]
这个我昨天使用 win 测试了下，Terminal 本身不会影响的，我同样在 Windows Terminal 进行测试，在选用不同 shell 的情况下结果会有一定差异。我分别测试了 「PowerShell」、「Git Bash」、「cmd」三种 shell，并分别以「不带引号」、「单引号包裹」、「双引号包裹」传参进行测试（3x3=9 种情况），最终结果是只有「以 cmd 为 shell 且传参含单引号」时出现该问题。目测 PyCharm 上的问题也是将 cmd 作为 shell 引起的。

因此删去单引号或者将单引号改为双引号都是一种解决方案（个人倾向于后者），当然还有一种解决方案就是不要用 cmd 作为 shell 啦～๑乛ᆺ乛๑!!! PowerShell 和 Git Bash 不香嘛～～～
